### ISSUE TITLE
No interface showing.

### ISSUE THREAD

**Issue by Sourav2005** [irevenko/koneko#1]
I tried installing it using the given command in multiple different operating systems with no success.

`go get -u github.com/irevenko/koneko`

This is the result every single time.

![image](https://user-images.githubusercontent.com/61320974/117918124-177b5100-b308-11eb-8890-cb8cda8a5833.png)
![image](https://user-images.githubusercontent.com/61320974/117918153-26620380-b308-11eb-9cd6-772011d6915d.png)

**Comment by irevenko** [comment]
just increase terminal size

**Comment by Sourav2005** [comment]
> just increase terminal size

does not work I did it multiple times. 


https://user-images.githubusercontent.com/61320974/117971734-e15dc180-b347-11eb-85d4-6cdea6b51a67.mp4

**Comment by irevenko** [comment]
decrease font size
what is ur resolution?

**Comment by Sourav2005** [comment]
my resolution is 1366x768.  Do you think this is causing problems? I will update after trying it on my sister's laptop. She has a 1080p screen. also I did try with decreased font size, still did not work.

Edit : it worked after I decreased my font size to 5 lol. Thanks for helping!

Btw it does not seem to open the torrent client on Windows when I press Ctrl+O. It is not an issue for me though since it does download the torrent files into the directory.

**Comment by irevenko** [comment]
🤗

**Comment by Sourav2005** [comment]
> 🤗

lol I edited the comment please see it again.

**Comment by irevenko** [comment]
yes it is having some problems with windows, i need to check this

**Comment by Sourav2005** [comment]
Thank you! also thanks for resolving my stupid mistake.

**Comment by irevenko** [comment]
no problem if you need any help or questions just message in Discord **Ilya Revenko#4742** or Telegram **@irevenko**
