### ISSUE TITLE
Ctrl + H clashes with Backspace on windows terminal

### ISSUE THREAD

**Issue by darylhjd** [irevenko/koneko#2]
Seems to be how control keys work in general.

tcell documentation:

`These are the control keys. Note that they overlap with other keys, perhaps. For example, KeyCtrlH is the same as KeyBackspace.`

The only possible fix would be to change the hotkeys.

tcell issue: https://github.com/gdamore/tcell/issues/204

**Comment by irevenko** [comment]
this is 👌

**Comment by irevenko** [comment]
no this is not 😂

**Comment by irevenko** [comment]
PogU
https://github.com/irevenko/koneko/commit/cc3a8d2a609f19064ab42c9e903fef10935a8e1f
